syntax = "proto3";

package user;

service AuthService {
  rpc RegisterUser (RegisterUserRequest) returns (RegisterUserResponse);
}

message NoParam {}

message RegisterUserRequest {
  string          email           = 1;
  string          username        = 2;
  string          password        = 3;
  string          confirmPassword = 4;
  optional string displayName     = 5;
}

message RegisterUserResponse {
  int32           id           = 1;
  string          email        = 2;
  string          username     = 3;
  optional string displayName  = 4;
  string          accessToken  = 5;
  string          refreshToken = 6;
}
